# Generated by Django 5.2 on 2025-04-16 07:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('yaml_content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('kafka_to_kafka', 'Kafka to Kafka Replay'), ('kafka_to_mq', 'Kafka to MQ Replay'), ('mq_to_mq', 'MQ to MQ Replay'), ('mq_to_kafka', 'MQ to Kafka Replay'), ('db_operation', 'DB Updates and Queries')], max_length=50)),
                ('action_config', models.TextField()),
                ('order', models.IntegerField()),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow_builder.workflow')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
