# Generated by Django 5.2 on 2025-04-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_builder', '0002_workflowstep_trigger_from_workflowstep_trigger_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowstep',
            old_name='action_config',
            new_name='from_config',
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='trigger_from',
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='trigger_to',
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='trigger_type',
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='event_type',
            field=models.CharField(choices=[('replay', 'Replay'), ('dump', 'Dump'), ('extract', 'Extract'), ('transform', 'Transform'), ('load', 'Load')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='from_infra',
            field=models.CharField(choices=[('kafka', 'Kafka'), ('mq', 'MQ'), ('db', 'Database'), ('servicebus', 'Service Bus'), ('file', 'File System')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='to_config',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='to_infra',
            field=models.CharField(choices=[('kafka', 'Kafka'), ('mq', 'MQ'), ('db', 'Database'), ('servicebus', 'Service Bus'), ('file', 'File System')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
