# Generated by Django 5.2 on 2025-04-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_builder', '0004_actionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstep',
            name='event_type',
            field=models.CharField(choices=[('replay', 'Replay'), ('dump', 'Dump'), ('extract', 'Extract'), ('transform', 'Transform'), ('load', 'Load'), ('kafka_dump', 'Kafka Dump'), ('mq_dump', 'MQ Dump')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='to_config',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='to_infra',
            field=models.CharField(blank=True, choices=[('kafka', 'Kafka'), ('mq', 'MQ'), ('db', 'Database'), ('servicebus', 'Service Bus'), ('file', 'File System')], max_length=50, null=True),
        ),
    ]
