# Generated by Django 5.2 on 2025-05-02 12:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_builder', '0006_workflowexecution_stepexecution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('workflow_save', 'Workflow Save'), ('workflow_execute', 'Workflow Execute')], max_length=50)),
                ('workflow_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver1', models.CharField(blank=True, max_length=100, null=True)),
                ('approver1_time', models.DateTimeField(blank=True, null=True)),
                ('approver2', models.CharField(blank=True, max_length=100, null=True)),
                ('approver2_time', models.DateTimeField(blank=True, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='workflow_builder.workflow')),
            ],
        ),
    ]
